# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    acl:
        connection: default
#    role_hierarchy:
#        ROLE_SONATA_CMS:
#            - ROLE_ADMIN_CONTACTMESSAGE_ALL
#            - ROLE_ADMIN_COWORKER_ALL
#            - ROLE_ADMIN_CATEGORY_ALL
#        ROLE_SONATA_MANAGER:
#            - ROLE_ADMIN_USER_ALL
#        ROLE_CMS:
#            - ROLE_USER
#            - ROLE_SONATA_CMS
#            - ROLE_SONATA_ADMIN
#        ROLE_ADMIN:
#            - ROLE_CMS
#            - ROLE_SONATA_MANAGER
#        ROLE_SUPER_ADMIN:
#            - ROLE_ADMIN
#            - ROLE_ALLOWED_TO_SWITCH
    access_decision_manager:
        strategy: unanimous
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: /admin(.*)
            context: user
            form_login:
                provider:                       fos_userbundle
                login_path:                     /admin/login
                use_forward:                    false
                check_path:                     /admin/login_check
                failure_path:                   /admin/login
                default_target_path:            /admin/dashboard
                always_use_default_target_path: true
                use_referer:                    true
            logout:
                path:   /admin/logout
                target: /admin/login
            anonymous: true
    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_USER }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
